name: Bitalarm
description: Cryptocurrency tracker and portfolio

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  nav_router: 0.0.5
  dio: 3.0.9
  hive: 1.4.1+1
  hive_flutter: 0.3.0+2
  provider: 4.0.5+1
  qrscan: 0.2.17
  dio_http_cache: 0.2.6
  flutter:
    sdk: flutter

dev_dependencies:
  hive_generator: 0.7.0+2
  build_runner: 1.9.0
  flutter_launcher_icons: 0.7.5

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Bold.ttf
        - asset: assets/fonts/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald-Light.ttf
